---
 - name: Get PHP Repository
   yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

 - name: Upgrade Packages
   yum: 
    name: '*'
    state: latest

 - name: Install PHP 7
   yum:
    name: "{{ item }}"
    state: latest
   with_items:
    - php70
    - php70-php-mysqlnd
   when: php_version == 7

 - name: Install PHP 5
   yum:
    name: "{{ item }}"
    state: latest
   with_items:
    - php55
    - php55-php-mysqlnd
   when: php_version == 5

 - name: Replace PHP Config File
   copy:
    src: php.ini
    dest: /etc/
    owner: root
    group: root
    mode: 0644